FROM openjdk:8u232-jre-slim
RUN apk add --no-cache curl tar
VOLUME /tmp
ARG APPLICATION_NAME=restTestApi
ARG VERSION=0.0.1-SNAPSHOT
ARG JAR_FILE=target/${APPLICATION_NAME}-${VERSION}.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]